apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: golang-oauth-api
  name: golang-oauth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-oauth-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: golang-oauth-api
    spec:
      containers:
      - image: golang
        name: golang-oauth-api
        ports:
        - containerPort: 8081
        command: ["/bin/sh", "-c"]
        args:
          - go get -u github.com/gin-gonic/gin;
            go get -u github.com/stretchr/testify/assert;
            git clone https://github.com/ninoude/bookstore_oauth-api.git $GOPATH/src/github.com/ninoude/bookstore_oauth-api/;
            apt update;
            apt install -y vim;
            sleep 360000000;
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: golang-oauth-api
  name: golang-oauth-api
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30081
  selector:
    app: golang-oauth-api
  type: NodePort
status:
  loadBalancer: {}
