apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: golang
  name: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: golang
    spec:
      containers:
      - image: golang
        name: golang
        ports:
        - containerPort: 8080
        command: ["/bin/sh", "-c"]
        args:
          - go get -u github.com/gin-gonic/gin;
            go get -u github.com/go-sql-driver/mysql;
            go get -u go.uber.org/zap;
            git clone https://github.com/ninoude/bookstore_users-api.git $GOPATH/src/github.com/ninoude/bookstore_users-api/;
            apt update;
            apt install -y vim mariadb-client;
            sleep 360000000;
        envFrom:
        - secretRef:
            name: golang-secret
          prefix: MYSQL_USERS_
---
apiVersion: v1
kind: Secret
metadata:
  name: golang-secret
data:
  HOST: bXlzcWwtc3ZjOjMzMDY=
  PASSWORD: UGFzc3cwcmQh
  SCHEMA: dXNlcnNfZGI=
  USERNAME: cm9vdA==

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: golang
  name: golang
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: golang
  type: NodePort
status:
  loadBalancer: {}
