apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: golang
  name: golang
spec:
  containers:
  - image: golang:1.15.2
    name: golang
    command: ["/bin/sh", "-c"]
    envFrom:
    - secretRef:
        name: golang-secret
      prefix: MYSQL_USERS_
    args:
      - go get -u github.com/gin-gonic/gin;
        go get -u github.com/go-sql-driver/mysql;
        git clone https://github.com/ninoude/bookstore_users-api.git $GOPATH/src/github.com/ninoude/bookstore_users-api/;
        apt update;
        apt install -y vim mariadb-client;
        sleep 36000;
#        go run $GOPATH/src/github.com/ninoude/bookstore_users-api/main.go;
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: golang
  name: golang-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    run: golang
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: golang-secret
data:
  HOST: bXlzcWwtc3ZjOjMzMDY=
  PASSWORD: UGFzc3cwcmQh
  SCHEMA: dXNlcnNfZGI=
  USERNAME: cm9vdA==
