apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: mysql
    name: mysql
    envFrom:
    - secretRef:
        name: mysql-secret
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: default-auth
      mountPath: /etc/mysql/conf.d
    - name: init-db
      mountPath: /docker-entrypoint-initdb.d
  volumes:
  - name: default-auth
    hostPath:
      path: ./db/confd
      type: Directory
  - name: init-db
    hostPath:
      path: ./db/initd
      type: Directory
---
apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: UGFzc3cwcmQh
kind: Secret
metadata:
  name: mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql-svc
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
status:
  loadBalancer: {}
